name = "Cozy Days"
author = "unluckyGolem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3632d00ac3b0614e88c21adf52974377d34c998418d562dca034002b9afa831e"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
