name = "Cozy Days"
author = "unluckyGolem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9851b392fce2a7e6d004896fb579cb0b4ddd009b084ab1c7f46426142b1cfcf"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
