name = "Cozy Days"
author = "unluckyGolem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0424d1e0abf103e1718054fedb92a42c5278b90d1521db3e31f09d67f77e222"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
