name = "2026 Minecraft Server"
author = "unluckyGolem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30bde16d828688f3b9848a0891dbc6887a59454eda544ff84eafebc23ce76094"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
