name = "2026 Minecraft Server"
author = "unluckyGolem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01562d8a217995921e7ef13493a26cf2fc2d493d919ee10f36a1dfe3dce775cf"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
