name = "2026 Minecraft Server"
author = "unluckyGolem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3d5862c6c442b432fd227ceb7b3821b07eb698ac42b19b51f3639adec7bf542"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
